require:
  - rubocop-thread_safety
  - rubocop-rspec
  - rubocop-performance

inherit_from:
  - .rubocop_general.yml
  - .rubocop_rspec.yml
  - .rubocop-thread_safety.yml
  - .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
