#require: rubocop-thread_safety
#require: rubocop-rspec

inherit_from:
  - .rubocop_general.yml
#  - .rubocop_rspec.yml
#  - .rubocop-thread_safety.yml
  - .rubocop_todo.yml

# Enable when all supported ruby will support feature
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
