version: 2

jobs:
  "Run tests on ruby 2.6.4":
    docker:
      - image: circleci/ruby:2.6.4
    working_directory: ~/circleci
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: gem install bundler -v '2.0.2'
      - run: bundle install
      - run: bundle exec rake

workflows:
  version: 2
  build:
    jobs:
      - "Run tests on ruby 2.6.4"
