version: 2

jobs:
  ruby-2.5.8:
    docker:
      - image: circleci/ruby:2.5.8
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec mdl README.md CHANGELOG.md TODO.md
  ruby-2.6.6:
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec mdl README.md CHANGELOG.md TODO.md
  ruby-2.7.1:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec mdl README.md CHANGELOG.md TODO.md

workflows:
  version: 2
  tests:
    jobs:
      - ruby-2.5.8
      - ruby-2.6.6
      - ruby-2.7.2
