version: 2

jobs:
  ruby-2.5.8:
    docker:
      - image: circleci/ruby:2.5.8
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal activesupport_50 rake
      - run: bundle exec appraisal activesupport_51 rake
      - run: bundle exec appraisal activesupport_52 rake
      - run: bundle exec appraisal activesupport_60 rake
      - run: bundle exec appraisal activesupport_edge rake
      - run: bundle exec standardrb
      - run: bundle exec mdl README.md CHANGELOG.md TODO.md
  ruby-2.6.6:
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal activesupport_50 rake
      - run: bundle exec appraisal activesupport_51 rake
      - run: bundle exec appraisal activesupport_52 rake
      - run: bundle exec appraisal activesupport_60 rake
      - run: bundle exec appraisal activesupport_edge rake
      - run: bundle exec standardrb
      - run: bundle exec mdl README.md CHANGELOG.md TODO.md
  ruby-2.7.1:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal activesupport_50 rake
      - run: bundle exec appraisal activesupport_51 rake
      - run: bundle exec appraisal activesupport_52 rake
      - run: bundle exec appraisal activesupport_60 rake
      - run: bundle exec appraisal activesupport_edge rake
      - run: bundle exec standardrb
      - run: bundle exec mdl README.md CHANGELOG.md TODO.md
  jruby-9.2.11.1:
    docker:
      - image: circleci/jruby:9.2.11.1
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal activesupport_42 rake JRUBY_OPTS="--debug"
      - run: bundle exec appraisal activesupport_50 rake JRUBY_OPTS="--debug"
      - run: bundle exec appraisal activesupport_51 rake JRUBY_OPTS="--debug"
      - run: bundle exec appraisal activesupport_52 rake JRUBY_OPTS="--debug"
      - run: bundle exec appraisal activesupport_60 rake JRUBY_OPTS="--debug"
      - run: bundle exec appraisal activesupport_edge rake JRUBY_OPTS="--debug"
      - run: bundle exec standardrb
      - run: bundle exec mdl README.md CHANGELOG.md TODO.md

workflows:
  version: 2
  tests:
    jobs:
      - jruby-9.2.11.1
      - ruby-2.5.8
      - ruby-2.6.6
      - ruby-2.7.1
