version: 2

jobs:
  "Run tests on ruby 2.6.4 with activesupport 6.0":
    docker:
      - image: circleci/ruby:2.6.4
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_GEMFILE: gemfiles/activesupport_60.gemfile
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: gem install bundler -v '2.0.2'
      - restore_cache:
          keys:
            - gem-cache-v1-{{ .Branch }}
            - gem-cache-v1-
      - run: bundle install
      - run: bundle clean
      - save_cache:
          - keys:
              - gem-cache-v1-{{ .Branch }}
      - run: bundle exec rake

workflows:
  version: 2
  build:
    jobs:
      - "Run tests on ruby 2.6.4 with activesupport 6.0"
