name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - v2.4.x
          - v2.5.x
          - v2.6.x
          - v2.7.x
        gemfile:
          - gemfiles/activesupport_42.gemfile
          - gemfiles/activesupport_50.gemfile
          - gemfiles/activesupport_51.gemfile
          - gemfiles/activesupport_52.gemfile
          - gemfiles/activesupport_60.gemfile
          - gemfiles/activesupport_edge.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        ls -la /opt/hostedtoolcache/Ruby/
        gem update --system || true
        gem install bundler || true
        bundle install --jobs 4 --retry 3
        bundle exec rake
